apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-serve-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-serve
      version: v2
  template:
    metadata:
      labels:
        app: go-serve
        version: v2
    spec:
      containers:
      - image: docker.io/mkyo114/go-serve:v2
        name: go-serve
        ports:
        - containerPort: 80
      nodeSelector:
        topology.kubernetes.io/zone: kubernetes.io/hostname=istio3
