apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: go-serve
spec:
  host: go-serve
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: ap-northeast
          to:
            "ap-northeast/az2/*" : 90
            "ap-northeast/az1/*" : 10
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 3m