apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: go-serve
spec:
  host: go-serve
  subsets:
    - labels:
        version: v1
      name: subset-v1
    - labels:
        version: v2
      name: subset-v2
