apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: go-serve-dr
spec:
  host: go-serve
  subsets:
  - labels:
      version: v1
    name: subset-v1
  - labels:
      version: v2
    name: subset-v2
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: region1/az2/*
          to:
            "region1/az2/*": 99
            "region1/az1/*": 1
        - from: region1/az1/*
          to:
            "region/az2/*": 99
            "region/az1/*": 1