apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: go-serve-vs
spec:
  hosts:
    - go-serve-vs
  http:
    - match:
        - headers:
            end-user:
              exact: jason
      route:
        - destination:
            host: go-serve-v2
            subset: subset-v1
          weight: 20
        - destination:
            host: go-serve-v2
            subset: subset-v2
          weight: 80
    - route:
        - destination:
            host: go-serve
            subset: subset-v1
          weight: 90
        - destination:
            host: go-serve
            subset: subset-v2
          weight: 10
